# 代理服务器配置
# host
server-host: 0.0.0.0

# 代理服务器数据传输port
server-port: 9879

data-min-port: 10000
data-max-port: 11000
# user
user:
  - key: 1234
  - key: 4567
  - key: 2345
  - key: 12342
  - key: 2134321
# path: C:\Users\Administrator\Desktop\data

path: /Users/wuyh/work/中行金网/FTP/b
